version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 1234
      MARIADB_DATABASE: PEPS
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Peliculas.sql:/docker-entrypoint-initdb.d/Peliculas.sql
    ports:
      - "3306:3306"
    networks:
      - my_network

  apache:
    build: ./apache
    container_name: apache
    ports:
      - 7777:80
    restart: unless-stopped
    volumes:
      - /static:/var/www/html:rw

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - MARIADB_ROOT_PASSWORD=1234
    ports:
      - "9093:80"
    depends_on:
      - mariadb
    networks:
      - my_network

  python:
    build: .
    container_name: python
    environment:
      PYTHONBUFFERED: 1
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - "9094:8080"
    depends_on:
      - mariadb
    networks:
      - my_network
    

volumes:
  mariadb_data:

networks:
  my_network:

 
